print('hello world')
print('what is your name?')
myname= input()
print('it is good to meet you , ' + myname)
print('what is your age?')
myage = input()
print ('you will be' + str(int(myage) + 1) + 'in a year')
